[buildPlans.iosevka-mono]
family = "Iosevka Mono"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

  [buildPlans.iosevka-mono.variants]
  inherits = "ss14"

    [buildPlans.iosevka-mono.variants.design]
    capital-j = "serifed"
    capital-k = "straight-serifless"
    capital-q = "crossing"
    capital-w = "straight-serifless"
    k = "straight-serifless"
    l = "serifed"
    r = "compact-serifed"
    u = "toothed-serifless"
    y = "straight-turn-serifless"
    long-s = "flat-hook-tailed"
    eszet = "sulzbacher-descending-serifless"
    lower-alpha = "crossing"
    zero = "oval-tall-slashed"
    one = "no-base"
    seven = "straight-serifless"
    asterisk = "hex-low"
    paren = "normal"
    ampersand = "closed"
    at = "fourfold-solid-inner"
    question = "smooth"

    [buildPlans.iosevka-mono.variants.italic]
    capital-j = "serifed"
    capital-k = "straight-serifless"
    capital-q = "crossing"
    capital-w = "straight-serifless"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    g = "single-storey-flat-hook-earless-corner"
    i = "serifed-flat-tailed"
    k = "straight-serifless"
    l = "serifed-flat-tailed"
    m = "earless-single-arch-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "earless-corner-serifless"
    u = "toothless-corner-serifless"
    y = "cursive-flat-hook-serifless"
    long-s = "flat-hook-tailed"
    eszet = "sulzbacher-descending-serifless"
    lower-alpha = "crossing"
    zero = "oval-tall-slashed"
    one = "no-base"
    seven = "straight-serifless"
    asterisk = "hex-low"
    paren = "normal"
    ampersand = "closed"
    at = "fourfold-solid-inner"

[buildPlans.iosevka-mono.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-mono.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
